controller:
  workflowNamespaces:
    - workflows
  workflowDefaults:
    spec:
      serviceAccountName: argo-workflows-sa
server:
  baseHref: /argo/
  serviceAccount:
    create: true
  extraArgs:
    - server
    - --auth-mode=server
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    paths:
      - /argo/(.*)
      - /argo
    pathType: ImplementationSpecific